swagger: "2.0"
info:
  title: API
  description: API using microservice architecture
  version: 1.0.0

host: localhost:8081
basePath: /
schemes:
  - http

consumes:
  - application/json
produces:
  - application/json

paths:
  /user/login:
    post:
      summary: Get token for the user.
      parameters:
        - in: body
          name: user
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: OK
  /user/register:
    post:
      summary: Add new user to system.
      parameters:
        - in: body
          name: register
          schema:
            $ref: '#/definitions/Register'
      responses:
        201:
          description: User created.
        422:
          description: Unprocessable data.

definitions:
  User:
    properties:
      username:
        type: string
      password:
        type: string
    required:  
      - username
      - password
  Register:
    properties:
      username:
        type: string
      password:
        type: string
    required:  
      - username
      - password
